# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /posts/:year/:title

# Setup
title:            Hoburg Research Group
description:      "part of the Department of Aeronautics and Astronautics at MIT"
url:              http://hoburg.mit.edu
baseurl:          /

author:
  name:           'Hoburg Research Group'
  url:            http://hoburg.mit.edu

paginate:         5
paginate_path: "/posts/:num"

roles:
    - {key: Principal Investigator, name: Principal Investigator, display: full}
    - {key: PhD Student, name: PhD Student, display: full}
    - {key: Master's Student, name: Master's Student, display: full}
    - {key: Undergraduate Researcher, name: Undergraduate Researcher, display: full}
    - {key: Alumni, name: Alumni, display: short}
