# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        /posts/:year/:title

# Setup
title:            Hoburg Research Group
description:      "part of the Department of Aeronautics and Astronautics at MIT"
url:              http://hoburg.mit.edu
baseurl:          /

author:
  name:           'Hoburg Research Group'
  url:            http://hoburg.mit.edu

paginate:         5
paginate_path: "/posts/:num"
