# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /posts/:year/:title

# Setup
title:            Hoburg Research Group
description:      "part of the Aerospace Computational Design Lab at MIT"
url:              http://aeroa.mit.edu
baseurl:          /

author:
  name:           'Hoburg Research Group'
  url:            http://aeroa.mit.edu

paginate:         5
paginate_path: "/posts/:num"
